package com.management.school.service;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
// The generic Font import is ambiguous, so we will use fully qualified names
// in the methods where 'Font' is needed.

import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;

import java.io.FileOutputStream;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

@Service
public class ReportService {

    /**
     * Export report content to PDF
     */
    public void exportToPdf(String content, String filePath) throws Exception {
        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, new FileOutputStream(filePath));
        
        document.open();
        
        // Add metadata
        document.addTitle("School Management Report");
        document.addAuthor("School Management System");
        document.addCreator("School Management System");
        document.addCreationDate();
        
        // Set font for content
        // Use the fully qualified name for iText's Font class
        com.itextpdf.text.Font font = FontFactory.getFont(FontFactory.COURIER, 9, BaseColor.BLACK);
        
        // Split content by lines and add to document
        String[] lines = content.split("\n");
        for (String line : lines) {
            Paragraph para = new Paragraph(line, font);
            para.setAlignment(Element.ALIGN_LEFT);
            document.add(para);
        }
        
        // Add footer
        // Use the fully qualified name for iText's Font class
        com.itextpdf.text.Font footerFont = FontFactory.getFont(FontFactory.HELVETICA, 8, BaseColor.GRAY);
        Paragraph footer = new Paragraph("\n\nGenerated by School Management System on " + 
                                           LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")), 
                                           footerFont);
        footer.setAlignment(Element.ALIGN_CENTER);
        document.add(footer);
        
        document.close();
    }

    /**
     * Export report content to Excel
     */
    public void exportToExcel(String content, String filePath) throws IOException {
        Workbook workbook = new XSSFWorkbook();
        Sheet sheet = workbook.createSheet("Report");
        
        // Create header style
        CellStyle headerStyle = workbook.createCellStyle();
        // Use the fully qualified name for Apache POI's Font interface
        org.apache.poi.ss.usermodel.Font headerFont = workbook.createFont();
        headerFont.setBold(true);
        headerFont.setFontHeightInPoints((short) 12);
        headerStyle.setFont(headerFont);
        headerStyle.setAlignment(HorizontalAlignment.CENTER);
        
        // Create data style
        CellStyle dataStyle = workbook.createCellStyle();
        // Use the fully qualified name for Apache POI's Font interface
        org.apache.poi.ss.usermodel.Font dataFont = workbook.createFont();
        dataFont.setFontName("Courier New");
        dataFont.setFontHeightInPoints((short) 10);
        dataStyle.setFont(dataFont);
        
        // Split content into lines
        String[] lines = content.split("\n");
        
        int rowNum = 0;
        for (String line : lines) {
            Row row = sheet.createRow(rowNum++);
            Cell cell = row.createCell(0);
            cell.setCellValue(line);
            
            // Apply style based on content
            if (line.contains("═══") || line.contains("REPORT")) {
                cell.setCellStyle(headerStyle);
            } else {
                cell.setCellStyle(dataStyle);
            }
        }
        
        // Auto-size column
        sheet.setColumnWidth(0, 20000);
        
        // Add metadata sheet
        Sheet metadataSheet = workbook.createSheet("Metadata");
        Row metaRow1 = metadataSheet.createRow(0);
        metaRow1.createCell(0).setCellValue("Generated By:");
        metaRow1.createCell(1).setCellValue("School Management System");
        
        Row metaRow2 = metadataSheet.createRow(1);
        metaRow2.createCell(0).setCellValue("Generated On:");
        metaRow2.createCell(1).setCellValue(LocalDateTime.now().format(
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
        
        metadataSheet.setColumnWidth(0, 5000);
        metadataSheet.setColumnWidth(1, 7000);
        
        // Write to file
        try (FileOutputStream fileOut = new FileOutputStream(filePath)) {
            workbook.write(fileOut);
        }
        
        workbook.close();
    }

    /**
     * Generate a formatted report header
     */
    public String generateReportHeader(String reportTitle, String... metadata) {
        StringBuilder header = new StringBuilder();
        header.append("═══════════════════════════════════════════════════════\n");
        header.append(centerText(reportTitle, 55)).append("\n");
        header.append("═══════════════════════════════════════════════════════\n");
        
        for (String meta : metadata) {
            header.append(meta).append("\n");
        }
        
        header.append("───────────────────────────────────────────────────────\n\n");
        return header.toString();
    }

    /**
     * Generate a formatted report footer
     */
    public String generateReportFooter() {
        StringBuilder footer = new StringBuilder();
        footer.append("\n═══════════════════════════════════════════════════════\n");
        footer.append(centerText("END OF REPORT", 55)).append("\n");
        footer.append("═══════════════════════════════════════════════════════\n");
        return footer.toString();
    }

    /**
     * Center text within a given width
     */
    private String centerText(String text, int width) {
        int padding = (width - text.length()) / 2;
        return " ".repeat(Math.max(0, padding)) + text;
    }

    /**
     * Format a table row
     */
    public String formatTableRow(int width, String... columns) {
        StringBuilder row = new StringBuilder();
        int colWidth = width / columns.length;
        
        for (String column : columns) {
            String formatted = String.format("%-" + colWidth + "s", 
                column.length() > colWidth ? column.substring(0, colWidth - 3) + "..." : column);
            row.append(formatted);
        }
        
        return row.toString();
    }
}